<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Preview {{ $permohonan->layanan->nama }}</title>
<style>
@page{size:A4;margin:0}*{box-sizing:border-box}body{margin:0;background:#e5e7eb;font-family:Arial,sans-serif;color:#111}.toolbar{height:64px;background:#fff;border-bottom:1px solid #ddd;display:flex;align-items:center;justify-content:space-between;padding:0 24px;position:sticky;top:0;z-index:3}.toolbar h2{font-size:17px;margin:0}.toolbar .btn{background:#0b5cff;color:#fff;border:0;border-radius:8px;padding:10px 16px;font-weight:700;cursor:pointer}.paper{width:210mm;min-height:297mm;margin:24px auto;background:#fff;padding:15mm 17mm;box-shadow:0 5px 22px rgba(0,0,0,.12);overflow:hidden}.kop{display:grid;grid-template-columns:25mm 1fr;column-gap:7mm;align-items:center;padding-bottom:4mm;border-bottom:1.4mm solid #111;position:relative}.logo{width:24mm;height:24mm;object-fit:contain}.kop-text{text-align:center}.pemerintah{font-size:14pt;font-weight:700}.kecamatan{font-size:16pt;font-weight:700}.alamat{font-size:8.5pt;margin-top:1mm}.judul{text-align:center;margin:7mm 0 5mm}.judul h1{font-size:12pt;text-decoration:underline;margin:0 0 2mm}.nomor{font-size:9pt}.isi{font-size:10.5pt;line-height:1.48;white-space:normal}.signature{width:62mm;margin-left:auto;margin-top:10mm;text-align:center;font-size:9.5pt}.signature img{display:block;width:47mm;height:27mm;object-fit:contain;margin:2mm auto}.qr{width:18mm;height:18mm;border:1px solid #222;margin:3mm auto;display:flex;align-items:center;justify-content:center;font-size:7pt;font-weight:700}.nama-pejabat{font-weight:700;text-decoration:underline;margin-top:1mm}@media print{body{background:#fff}.toolbar{display:none}.paper{margin:0;box-shadow:none;width:210mm;min-height:297mm;height:297mm;padding:15mm 17mm}}
</style></head>
<body>
<div class="toolbar"><h2>Preview Surat · {{ $permohonan->layanan->nama }}</h2><button class="btn" onclick="window.print()">🖨 Cetak Surat</button></div>
<div class="paper">
<div class="kop"><img class="logo" src="{{ asset('assets/logo-kota-magelang.jpg') }}" alt="Logo Kota Magelang"><div class="kop-text"><div class="pemerintah">PEMERINTAH KOTA MAGELANG</div><div class="kecamatan">KECAMATAN MAGELANG UTARA</div><div class="alamat">Kantor Kecamatan Magelang Utara · Kota Magelang</div></div></div>
<div class="judul"><h1>{{ $permohonan->layanan->templateSurat->judul }}</h1><div class="nomor">Nomor: {{ '470/' . str_pad($permohonan->id,4,'0',STR_PAD_LEFT) . '/KMU' }}</div></div>
<div class="isi">{!! nl2br($surat) !!}</div>
<div class="signature"><div>Magelang, {{ now()->translatedFormat('d F Y') }}</div><div style="margin-top:2mm">{{ config('penandatangan.jabatan') }}</div><img src="{{ asset('assets/ttd-camat.png') }}" alt="Tanda tangan elektronik"><div>Ditandatangani secara elektronik</div><div class="qr">QR<br>DUMMY</div><div class="nama-pejabat">{{ config('penandatangan.nama') }}</div></div>
</div>
</body></html>